In [59]:
import numpy as np
import matplotlib.pyplot as plt


# Sample Data
X1_study_hrs = np.array([10,15,8,12,6]) 
X2_sleep_hrs = np.array([7,6,8,5,9]) 
X3_practice_tests = np.array([2,4,1,3,0]) 
y_score = np.array([75,85,70,78,65])

n = len(y_score)
# Prepare raw data
X  = np.column_stack((X1_study_hrs, X2_sleep_hrs, X3_practice_tests))
# Normalize features
X = (X - X.mean(axis=0)) / X.std(axis=0)
# Initialize weights and bias 
weights = np.zeros(3)
bias = 0
learning_rate = 0.01
iterations = 1000

# Storing History for animated graph 
planes = []

for i in range(iterations):
    y_pred = np.dot(X,weights) + bias 
    error = y_score - y_pred    
    cost = np.mean (error ** 2)
    
    # Gradients 
    # By transposing X, you flip the matrix so each feature becomes a row, 
    # and you can dot it with the error vector to see how much that feature is responsible 
    # for the error across all students.
    w_grad = -(2/n) * np.dot(X.T,error)
    b_grad = -(2/n) * np.sum(error)
    
    # Update 
    weights -= learning_rate*w_grad 
    bias -= learning_rate*b_grad 
    
    if (i%100==0):
        print("Weights {}, bias {}: Cost {}: Iterations {}".format(weights,bias,cost,i))
        
    # Store Place
    planes.append((weights.copy(),bias))


    
# To compare model values with linear regression
# Find W1,W2,W3 using linear regression 
from sklearn import linear_model
reg = linear_model.LinearRegression()
#X = np.column_stack((X1_study_hrs,X2_sleep_hrs,X3_practice_tests))
reg.fit(X,y_score)
print("weights {}, bias {}".format(reg.coef_, reg.intercept_))
print("\nGradient Descent weights:", weights)
print("Gradient Descent bias:", bias)

print("\nLinearRegression weights:", reg.coef_)
print("LinearRegression bias:", reg.intercept_)

 

Weights [ 0.13623124 -0.11596551  0.1357645 ], bias 1.4920000000000002: Cost 5611.8: Iterations 0
Weights [ 2.7905224  -1.36510854  2.63200445], bias 64.90444950764638: Cost 99.17487857803364: Iterations 100
Weights [ 3.1512136  -0.76651773  2.86369872], bias 73.3141803995489: Cost 2.4669657327033163: Iterations 200
Weights [ 3.40492441 -0.32794548  3.03055305], bias 74.42947517562742: Cost 0.4873368214321542: Iterations 300
Weights [ 3.58564204 -0.00963224  3.15499514], bias 74.57738507352265: Cost 0.3061043611292139: Iterations 400
Weights [3.71349893 0.22155084 3.2487227 ], bias 74.59700081849391: Cost 0.22594369205466638: Iterations 500
Weights [3.80306626 0.38961522 3.3201965 ], bias 74.5996022498806: Cost 0.18400196770123806: Iterations 600
Weights [3.8648995  0.51195509 3.37554558], bias 74.59994725055583: Cost 0.16185607937114893: Iterations 700
Weights [3.90664513 0.60117097 3.41920989], bias 74.59999300439215: Cost 0.1500941941723734: Iterations 800
Weights [3.93384237 0.6663

In [45]:
# Find W1,W2,W3 using linear regression 
from sklearn.preprocessing import StandardScaler
X = np.array([
    [10, 7, 2],
    [15, 6, 4],
    [8, 8, 1],
    [12, 5, 3],
    [6, 9, 0]
])
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

y_score = np.array([75,85,70,78,65])

from sklearn import linear_model
reg = linear_model.LinearRegression()
#X = np.column_stack((X1_study_hrs,X2_sleep_hrs,X3_practice_tests))
print(X_scaled)
reg.fit(X_scaled,y_score)
print("weights {}, bias {}".format(reg.coef_, reg.intercept_))


[[-0.06401844  0.          0.        ]
 [ 1.53644256 -0.70710678  1.41421356]
 [-0.70420284  0.70710678 -0.70710678]
 [ 0.57616596 -1.41421356  0.70710678]
 [-1.34438724  1.41421356 -1.41421356]]
weights [-6.24819974  2.82842712 15.55634919], bias 74.6


In [ ]:
10*-2 + 7*2 + 2*11 + 58.99 = 75.99

# 3.93384237 0.66639083 3.4544058 ], Bias=74.60
10*3.93 + 7*0.666 + 2*3.45 + 74.60 = 75.998