In [ ]:
# Numpy 
import numpy as np

# Array with rank 3
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

# Adding 1 number to every element of an array
arr2 = np.array([[5,6],[7,8]])
arr_add = arr2 + 1
print(arr_add)

# Substracting a number from every element of an array
arr_sub = arr2 - 1
print(arr_sub)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[6 7]
 [8 9]]
[[4 5]
 [6 7]]


In [ ]:
# shape/size/reshape properties 

arr1 = np.array([[1,2,3],[2,3,3]])
print(arr1.size) # number of elements 
print(arr1.shape) # size of array
arr2 = arr1.reshape(3,2) # Moved array from 2 * 3 matrix to 3 * 2 matrix
print(arr2)


6
(2, 3)
[[1 2]
 [3 2]
 [3 3]]


In [11]:
# Numpy  - assigning data types to each array
arr = np.array([[1,2],[3,4]])
print(arr.dtype)

arr = np.array([[1.0,2.1],[3.2,4.3]])
print(arr.dtype)

# Force data type while defnining an array
arr = np.array([[1.2,2.4],[5.2,44]],dtype=np.int64)
print(arr,arr.dtype)

int64
float64
[[ 1  2]
 [ 5 44]] int64


In [ ]:
# Array operations (Add, Sub, Transpose,Multiply -matmul) using numpy 
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[2,3],[1,2]])
arr_add = np.add(arr1,arr2)
print('Addition\n',arr_add)

# Array Sub
arr_sub = np.subtract(arr1,arr2)
print('Substraction\n',arr_sub)

# Array transpose
arr_trans = np.transpose(arr1)
print('Transpose\n',arr_trans)

# Matrix multiplication 
arr_mul = np.matmul(arr1,arr2)
print('Multiplication\n',arr_mul)


Addition
 [[3 5]
 [4 6]]
Substraction
 [[-1 -1]
 [ 2  2]]
Transpose
 [[1 3]
 [2 4]]
Multiplication
 [[ 4  7]
 [10 17]]


In [ ]:
# Flatten - convert 2D array to 1D by copying from the original array 
# Changes to flatten array wont impact main array 
arr1 = np.array([[1,2],[3,4]])
arr2 = arr1.flatten()
print(arr2)

[1 2 3 4]


In [ ]:
# Ravel - convert 2D Array to 1D - but uses only reference of the original array
arr1 = np.array([[1,2],[3,4]])
arr2 = arr1.ravel()
print(arr2)
arr2[1] = 100  # Changed value reflects in both arr2 and arr1 as it shared the same reference 
print(arr1,arr2)

[1 2 3 4]
[[  1 100]
 [  3   4]] [  1 100   3   4]


In [ ]:
# sum of each row 
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[2,3],[1,2]])
arr_add = arr1.sum(-1)
print(arr_add)

[3 7]


In [ ]:
# Slicing of an array(start, stop, step )
arr1 = np.arange(10)
print(arr1)
# slicing
print(arr1[1:5:1])  
print(arr1[5::])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]
[5 6 7 8 9]


In [ ]:
# Random function

# Random integers 1 D Array 
# ranint ()
# rand() # Generates values between 0 and 1 
# choice # random choice from a list 
# permutation # random values from a list
import numpy as np

arr1= np.random.randint(0,20,size= 5)
print(arr1)

# Generating 3x3 matrix between values 10 to 20
matrix = np.random.randint(10, 21, size=(3, 3))
print(matrix)

# Random 2D Array
arr1= np.random.rand(3,4) # generates an array of 3X4 matrix with values between 0 and 1 
print(arr1) 

# random choice from a list 
lst= ['blue','red','black','violet']
np.random.choice(lst,size=2)

# random permutation 
val = [1,2,3,4,5]
np.random.permutation (val)

[ 2  9 18 14  2]
[[0.34536898 0.63131642 0.71640472 0.84176337]
 [0.48831929 0.62075316 0.6094505  0.26853762]
 [0.86915508 0.13436458 0.05712319 0.76554044]]


array([1, 4, 3, 5, 2])

In [62]:
# linspace - generates evenly spaces numbers over a specified internval 
# Syntax np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

arr = np.linspace(1,10,50,retstep=True) # Generated 50 numbers between 1 to 10
print(arr)
arr = np.linspace(1,10,50,retstep=False) # Generated 50 numbers between 1 to 10
print(arr)





(array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]), np.float64(0.1836734693877551))
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  