In [37]:
import pandas as pd
from sklearn import linear_model

In [48]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4000       6.0   10  800000

In [52]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4000       6.0   10  800000

In [53]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)
reg.predict([[2500,3,30]])


c:\Users\ravis\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([485573.95166723])

In [51]:
reg.coef_

array([  102.51242001, 35165.03873358, -2111.82216234])

In [54]:
reg.intercept_

np.float64(187152.45031997282)

In [58]:
Price = (102.51242001 * 2500 )+ (35165.03873358*3) + (-2111.82216234 * 30 ) + 187152.45031997282
print(Price)

485573.9516755128


In [56]:
reg.predict([[3500,3,5]])

c:\Users\ravis\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([640881.92573257])

In [ ]:
# y = m1* area + m2 * bedrooms + M3.age + B
Price = (102.51242001 * 3500 )+ (35165.03873358*3) + (-2111.82216234 * 5 ) + 187152.45031997282
print(Price)