In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [11]:
# Loading CSV with home prices 
df = pd.read_csv("homeprices2.csv")
df


area  bedrooms  age   price
0  2000         3   20  550000
1  3000         4   15  565000
2  3200         3   18  610000
3  3600         3   30  680000
4  4000         5    8  760000

In [12]:
from sklearn import linear_model
reg = linear_model.LinearRegression()   
reg.fit(df[['area']],df.price)
print("coef: {}_, intercept:{}".format(reg.coef_,reg.intercept_))
reg.predict ([[5500]])

coef: [102.81690141]_, intercept:308098.59154929576


c:\Users\ravis\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([873591.54929577])

In [14]:
# Save the model using pickle
import pickle
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

with open('model_pickle','rb') as f:
    mp = pickle.load(f)

mp.predict([[5500]])
    

c:\Users\ravis\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([873591.54929577])

In [17]:
# Save the model using sklearn.joblib
import joblib
joblib.dump(reg,'model_joblib')
mp = joblib.load('model_joblib')
mp.predict([[5500]])


c:\Users\ravis\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([873591.54929577])